/**************************************************************************//**
 * @file     main.c
 * @version  V1.00
 * @brief    Demonstrate receiving IR data by CIR while Timer PWM drives
 *           the IR transmitter.
 *
 * SPDX-License-Identifier: Apache-2.0
 * @copyright (C) 2020 Nuvoton Technology Corp. All rights reserved.
 ****************************************************************************/
#include <stdio.h>
#include "NuMicro.h"

/*---------------------------------------------------------------------------------------------------------*/
/* Sample configuration                                                                                    */
/*---------------------------------------------------------------------------------------------------------*/
#define UART0_BAUD_RATE                 (115200U)       /*!< UART0 baud rate used by printf(). */

#define IR_CARRIER_FREQ_HZ              (38000U)        /*!< IR carrier frequency generated by Timer PWM. */
#define IR_CARRIER_DUTY_PERCENT         (50U)           /*!< IR carrier duty cycle. */
#define IR_FRAME_INTERVAL_US            (1000000U)      /*!< Delay between two transmitted IR frames. */
#define IR_DATA_BIT_COUNT               (32U)           /*!< Number of data bits in one IR frame. */

#define CIR_TIMING_UNIT_US              (26U)           /*!< Approximate CIR counter period when clocked by LIRC. */
#define CIR_PATTERN_SET_INDEX           (0U)            /*!< Pattern table index used by this sample. */

#define IR_TX_DATA_INITIAL              (0x12345678UL)  /*!< First data value transmitted by this sample. */
#define IR_TX_DATA_END                  (0x123456A0UL)  /*!< Stop the demonstration when this value is reached. */

/* Panasonic-compatible timing used by the AI-26C remote controller. Unit: microseconds. */
#define IR_HEADER_LOW_US                (9100U)
#define IR_HEADER_HIGH_US               (4450U)
#define IR_HEADER_DEVIATION             (50U)
#define IR_DATA0_LOW_US                 (576U)
#define IR_DATA0_HIGH_US                (557U)
#define IR_DATA0_DEVIATION              (15U)
#define IR_DATA1_LOW_US                 (576U)
#define IR_DATA1_HIGH_US                (1690U)
#define IR_DATA1_DEVIATION              (15U)
#define IR_SPECIAL_LOW_US               (9065U)
#define IR_SPECIAL_HIGH_US              (2282U)
#define IR_SPECIAL_DEVIATION            (15U)
#define IR_END_LOW_US                   (542U)
#define IR_END_HIGH_US                  (17000U)
#define IR_END_DEVIATION                (15U)

/**
 * @brief CIR receive-error handling notes.
 *
 * CIR_STATUS_RERRF_Msk is asserted when, for example:
 * 1. An incoming pulse width does not fall within any configured pattern boundary.
 * 2. For CIR_POSITIVE_EDGE or CIR_NEGATIVE_EDGE input types, the first received
 *    pattern does not match the configured header pattern.
 *
 * A repeat code or an end/stop pattern can arrive without a normal header. In
 * that case, the hardware may report a receive error even though the captured
 * timing is meaningful. The interrupt handler therefore compares the latched
 * timer value against the special-pattern and end-pattern boundaries.
 */

volatile uint32_t gu32ReceivedData0 = 0;
volatile uint32_t gu32ReceivedData1 = 0;
volatile uint32_t gu32TransmitData = IR_TX_DATA_INITIAL;

/**
 * @brief CIR interrupt handler.
 *
 * The handler distinguishes a receive-error event from a successfully matched
 * end pattern. For receive errors, the latched pulse width is checked against
 * the configured special and end-pattern windows so that repeat/end timing can
 * be identified separately from an invalid pulse.
 */
void CIR_IRQHandler(void)
{
    uint32_t status = CIR_GetIntFlag(CIR0) & CIR_GetEnabledIntMask(CIR0);

    if(status & CIR_STATUS_RERRF_Msk)
    {
        uint32_t u32Hb, u32Lb;

        /*
         * A repeat code can be reported as a receive error because it may not
         * be preceded by the normal header pattern. Check the captured timing
         * before treating the event as an actual receive error.
         */
        CIR_ClearIntFlag(CIR0, CIR_STATUS_RERRF_Msk);

        CIR_GetPatternBoundary(CIR0, CIR_SPECIAL_PAT, &u32Hb, &u32Lb);
        if((CIR_GetLatchedTimerValue(CIR0) < u32Hb) && (CIR_GetLatchedTimerValue(CIR0) > u32Lb))
            printf("Repeat\n");

        CIR_GetPatternBoundary(CIR0, CIR_END_PAT, &u32Hb, &u32Lb);
        if((CIR_GetLatchedTimerValue(CIR0) < u32Hb) && (CIR_GetLatchedTimerValue(CIR0) > u32Lb))
            printf("End\n");
        else
            printf("Error\n");
    }
    else if(status & CIR_STATUS_EPMF_Msk)
    {
        uint32_t u32Data0, u32Data1;

        /* The configured end pattern has been matched. */
        CIR_ClearIntFlag(CIR0, CIR_STATUS_EPMF_Msk);

        /* Read the decoded CIR data fields. This sample displays data field 0. */
        CIR_GetData(CIR0, &u32Data0, &u32Data1);
        gu32ReceivedData0 = u32Data0;

        /* Clear the data fields and bit count before receiving the next frame. */
        CIR_ClearDataFieldBitCount(CIR0);
    }
}

/**
 * @brief Initialize system clocks and multi-function pins used by this sample.
 */
void SYS_Init(void)
{
    /* Unlock protected registers before changing clock and pin settings. */
    SYS_UnlockReg();

    /* Enable HIRC and wait until it is stable. */
    CLK_EnableXtalRC(CLK_PWRCTL_HIRCEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_HIRCSTB_Msk);

    /* Enable HXT and wait until it is stable. */
    CLK_EnableXtalRC(CLK_PWRCTL_HXTEN_Msk);
    CLK_WaitClockReady(CLK_STATUS_HXTSTB_Msk);

    /* Run the CPU at 96 MHz from PLL. */
    CLK_SetCoreClock(FREQ_96MHZ);

    /* Set both PCLK0 and PCLK1 to HCLK/2. */
    CLK->PCLKDIV = (CLK_PCLKDIV_APB0DIV_DIV2 | CLK_PCLKDIV_APB1DIV_DIV2);

    /* Keep the original sample sequence unchanged. */
    CLK->PCLKDIV = (CLK_PCLKDIV_APB0DIV_DIV2 | CLK_PCLKDIV_APB1DIV_DIV2);

    /* Timer3 uses PCLK1 to generate the 38 kHz IR carrier. */
    CLK_SetModuleClock(TMR3_MODULE, CLK_CLKSEL1_TMR3SEL_PCLK1, 0);

    /* UART0 uses HIRC as its clock source. */
    CLK_SetModuleClock(UART0_MODULE, CLK_CLKSEL1_UART0SEL_HIRC, CLK_CLKDIV0_UART0(1));

    /* CIR uses LIRC. The resulting CIR counter period is approximately 26 us. */
    CLK_SetModuleClock(CIR0_MODULE, CLK_CLKSEL2_CIR0SEL_LIRC, (uint32_t)NULL);

    /* Enable clocks for all peripherals used by the sample. */
    CLK_EnableModuleClock(UART0_MODULE);
    CLK_EnableModuleClock(CIR0_MODULE);
    CLK_EnableModuleClock(TMR3_MODULE);

    /* Update SystemCoreClock and related CMSIS clock variables. */
    SystemCoreClockUpdate();

    /*-----------------------------------------------------------------------------------------------------*/
    /* Multi-function pin configuration                                                                    */
    /*-----------------------------------------------------------------------------------------------------*/

    /* PB12: UART0_RXD, PB13: UART0_TXD. */
    SYS->GPB_MFPH = (SYS->GPB_MFPH & ~(SYS_GPB_MFPH_PB12MFP_Msk | SYS_GPB_MFPH_PB13MFP_Msk)) |
                    (SYS_GPB_MFPH_PB12MFP_UART0_RXD | SYS_GPB_MFPH_PB13MFP_UART0_TXD);

    /* PF11: Timer3 PWM output used to drive the IR LED. */
    SYS->GPF_MFPH = (SYS->GPF_MFPH & ~(SYS_GPF_MFPH_PF11MFP_Msk));
    SYS->GPF_MFPH |= SYS_GPF_MFPH_PF11MFP_TM3;

    /* PC14: CIR0 receive input. */
    SYS->GPC_MFPH = (SYS->GPC_MFPH & ~SYS_GPC_MFPH_PC14MFP_Msk) | SYS_GPC_MFPH_PC14MFP_CIR0_RXD;

    /* Lock protected registers after initialization. */
    SYS_LockReg();
}

/**
 * @brief Initialize UART0 for console output.
 */
void UART0_Init(void)
{
    /* Reset UART0 to a known state. */
    SYS_ResetModule(UART0_RST);

    /* Configure UART0 for the console baud rate. */
    UART_Open(UART0, UART0_BAUD_RATE);
}

/**
 * @brief IR timing description used by this sample.
 *
 * Use an AI-26C generic remote controller configured for Panasonic TV mode:
 * hold "Setup" for about 3 seconds, then press "0", "0", "1".
 *
 * CIR clock source: LIRC, counter period ~= 26.04 us.
 * Timing values below are expressed in microseconds.
 *
 * Header : 9100 + 4450
 * Special: 9065 + 2282
 * Data 0 :  576 +  557
 * Data 1 :  576 + 1690
 * End    :  542 + 17000
 */
typedef struct tagTiming
{
    uint32_t u16Low;       /*!< Carrier-on duration or first timing segment, in microseconds. */
    uint32_t u16High;      /*!< Carrier-off duration or second timing segment, in microseconds. */
    uint32_t u16Deviation; /*!< Allowed CIR counter-count deviation for pattern matching. */
} S_TIME;

typedef struct tagPat
{
    S_TIME sHeadPat; /*!< Header pattern timing. */
    S_TIME sD0Pat;   /*!< Logical data-0 timing. */
    S_TIME sD1Pat;   /*!< Logical data-1 timing. */
    S_TIME sSpecPat; /*!< Special/repeat pattern timing. */
    S_TIME sEndPat;  /*!< End/stop pattern timing. */
} S_PAT;

/*
 * Keep protocol timing in one table so both the CIR receiver and Timer PWM
 * transmitter use the same timing definition.
 */
S_PAT sPatten[1] =
{
    IR_HEADER_LOW_US,  IR_HEADER_HIGH_US,  IR_HEADER_DEVIATION,
    IR_DATA0_LOW_US,   IR_DATA0_HIGH_US,   IR_DATA0_DEVIATION,
    IR_DATA1_LOW_US,   IR_DATA1_HIGH_US,   IR_DATA1_DEVIATION,
    IR_SPECIAL_LOW_US, IR_SPECIAL_HIGH_US, IR_SPECIAL_DEVIATION,
    IR_END_LOW_US,     IR_END_HIGH_US,     IR_END_DEVIATION
};

/**
 * @brief Initialize the CIR receiver according to the configured IR timings.
 *
 * The CIR hardware compares received pulse widths in counter ticks rather than
 * microseconds. Because one CIR tick is approximately 26 us in this sample,
 * each protocol timing is converted from microseconds to CIR counter counts.
 * A protocol-specific deviation is then added/subtracted to create the upper
 * and lower matching boundaries.
 */
void CIR_Init(void)
{
    uint32_t u32UpperBond, u32LowerBond;

    /* Use the CIR input clock without additional prescaling. */
    CIR_SetClockPrescaler(CIR0, CIR_PRESCALER_1);

    /* Configure header-pattern matching window. */
    u32UpperBond = ((sPatten[CIR_PATTERN_SET_INDEX].sHeadPat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sHeadPat.u16High) / CIR_TIMING_UNIT_US) + sPatten[CIR_PATTERN_SET_INDEX].sHeadPat.u16Deviation;
    u32LowerBond = ((sPatten[CIR_PATTERN_SET_INDEX].sHeadPat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sHeadPat.u16High) / CIR_TIMING_UNIT_US) - sPatten[CIR_PATTERN_SET_INDEX].sHeadPat.u16Deviation;
    CIR_SetPatternBoundary(CIR0, CIR_HEADER_PAT, u32UpperBond, u32LowerBond);

    /* Configure logical data-0 matching window. */
    u32UpperBond = ((sPatten[CIR_PATTERN_SET_INDEX].sD0Pat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sD0Pat.u16High) / CIR_TIMING_UNIT_US) + sPatten[CIR_PATTERN_SET_INDEX].sD0Pat.u16Deviation;
    u32LowerBond = ((sPatten[CIR_PATTERN_SET_INDEX].sD0Pat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sD0Pat.u16High) / CIR_TIMING_UNIT_US) - sPatten[CIR_PATTERN_SET_INDEX].sD0Pat.u16Deviation;
    CIR_SetPatternBoundary(CIR0, CIR_DATA0_PAT, u32UpperBond, u32LowerBond);

    /* Configure logical data-1 matching window. */
    u32UpperBond = ((sPatten[CIR_PATTERN_SET_INDEX].sD1Pat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sD1Pat.u16High) / CIR_TIMING_UNIT_US) + sPatten[CIR_PATTERN_SET_INDEX].sD1Pat.u16Deviation;
    u32LowerBond = ((sPatten[CIR_PATTERN_SET_INDEX].sD1Pat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sD1Pat.u16High) / CIR_TIMING_UNIT_US) - sPatten[CIR_PATTERN_SET_INDEX].sD1Pat.u16Deviation;
    CIR_SetPatternBoundary(CIR0, CIR_DATA1_PAT, u32UpperBond, u32LowerBond);

    /* Configure special/repeat-pattern matching window. */
    u32UpperBond = ((sPatten[CIR_PATTERN_SET_INDEX].sSpecPat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sSpecPat.u16High) / CIR_TIMING_UNIT_US) + sPatten[CIR_PATTERN_SET_INDEX].sSpecPat.u16Deviation;
    u32LowerBond = ((sPatten[CIR_PATTERN_SET_INDEX].sSpecPat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sSpecPat.u16High) / CIR_TIMING_UNIT_US) - sPatten[CIR_PATTERN_SET_INDEX].sSpecPat.u16Deviation;
    CIR_SetPatternBoundary(CIR0, CIR_SPECIAL_PAT, u32UpperBond, u32LowerBond);

    /* Configure end/stop-pattern matching window. */
    u32UpperBond = ((sPatten[CIR_PATTERN_SET_INDEX].sEndPat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sEndPat.u16High) / CIR_TIMING_UNIT_US) + sPatten[CIR_PATTERN_SET_INDEX].sEndPat.u16Deviation;
    u32LowerBond = ((sPatten[CIR_PATTERN_SET_INDEX].sEndPat.u16Low + sPatten[CIR_PATTERN_SET_INDEX].sEndPat.u16High) / CIR_TIMING_UNIT_US) - sPatten[CIR_PATTERN_SET_INDEX].sEndPat.u16Deviation;
    CIR_SetPatternBoundary(CIR0, CIR_END_PAT, u32UpperBond, u32LowerBond);

    /* Enable receive-error and end-pattern-match interrupts. */
    CIR_EnableInt(CIR0, CIR_INTCTL_PERRIEN_Msk | CIR_INTCTL_EPMIEN_Msk);

    /* Decode the received waveform using positive-edge timing with inverted input polarity. */
    CIR_SetInputType(CIR0, CIR_POSITIVE_EDGE, CIR_INVERSE);

    NVIC_EnableIRQ(CIR_IRQn);
    CIR_Open(CIR0);
}

/**
 * @brief Transmit one 32-bit IR frame through Timer3 PWM.
 * @param[in] u32IrData 32-bit payload. The least-significant bit is sent first.
 *
 * Timer3 continuously generates the IR carrier. TPWM_ENABLE_OUTPUT() gates that
 * carrier on and off to create the protocol's mark/space timing.
 */
void TPWM_IR_Transmitter(uint32_t u32IrData)
{
    int32_t i;

    /* Send the header: carrier ON for the low segment, then OFF for the high segment. */
    TPWM_ENABLE_OUTPUT(TIMER3, TPWM_CH0);
    CLK_SysTickDelay(sPatten[CIR_PATTERN_SET_INDEX].sHeadPat.u16Low);
    TPWM_ENABLE_OUTPUT(TIMER3, 0);
    CLK_SysTickDelay(sPatten[CIR_PATTERN_SET_INDEX].sHeadPat.u16High);

    /* Send 32 data bits, least-significant bit first. */
    for(i = 0; i <= ((int32_t)IR_DATA_BIT_COUNT - 1); i = i + 1)
    {
        if((u32IrData & BIT0) == BIT0)
        {
            /* Logical '1'. */
            TPWM_ENABLE_OUTPUT(TIMER3, TPWM_CH0);
            CLK_SysTickDelay(sPatten[CIR_PATTERN_SET_INDEX].sD1Pat.u16Low);
            TPWM_ENABLE_OUTPUT(TIMER3, 0);
            CLK_SysTickDelay(sPatten[CIR_PATTERN_SET_INDEX].sD1Pat.u16High);
        }
        else
        {
            /* Logical '0'. */
            TPWM_ENABLE_OUTPUT(TIMER3, TPWM_CH0);
            CLK_SysTickDelay(sPatten[CIR_PATTERN_SET_INDEX].sD0Pat.u16Low);
            TPWM_ENABLE_OUTPUT(TIMER3, 0);
            CLK_SysTickDelay(sPatten[CIR_PATTERN_SET_INDEX].sD0Pat.u16Low);
        }

        /* Move the next bit into BIT0. */
        u32IrData = u32IrData >> 1;
    }

    /* Send the final stop/end pattern. */
    TPWM_ENABLE_OUTPUT(TIMER3, TPWM_CH0);
    CLK_SysTickDelay(sPatten[CIR_PATTERN_SET_INDEX].sEndPat.u16Low);
    TPWM_ENABLE_OUTPUT(TIMER3, 0);
    CLK_SysTickDelay(sPatten[CIR_PATTERN_SET_INDEX].sEndPat.u16High);
}

/**
 * @brief Sample entry point.
 */
int main(void)
{
    uint32_t u32Data;

    /* Initialize system clocks, peripheral clocks, and multi-function pins. */
    SYS_Init();

    /* Initialize UART0 for console messages. */
    UART0_Init();

    /* Timer3 PWM provides the carrier used to drive the IR LED. */
    TPWM_ENABLE_PWM_MODE(TIMER3);
    printf("Timer3 PWM_CH0 on PF.11\n\n");

    /* Keep the carrier output disabled until a protocol mark is transmitted. */
    TPWM_ENABLE_OUTPUT(TIMER3, 0);

    /* Configure the IR carrier frequency and duty cycle in up-count mode. */
    u32Data = TPWM_ConfigOutputFreqAndDuty(TIMER3, IR_CARRIER_FREQ_HZ, IR_CARRIER_DUTY_PERCENT);
    if(u32Data != IR_CARRIER_FREQ_HZ)
        printf("Set the frequency %d different from the user's setting\n", u32Data);

    /* Start Timer3. The PWM output itself remains gated by TPWM_ENABLE_OUTPUT(). */
    TPWM_START_COUNTER(TIMER3);

    /* Initialize the CIR receiver with the same timing table used by the transmitter. */
    CIR_Init();

    do
    {
        /* Transmit the current test data and report the decoded CIR result. */
        TPWM_IR_Transmitter(gu32TransmitData);
        CLK_SysTickDelay(IR_FRAME_INTERVAL_US);
        printf("IR transmitted data 0x%x\n", gu32TransmitData);
        printf("CIR received data 0x%x....\n\n", gu32ReceivedData0);

        /* Repeat the test with the bitwise-inverted payload. */
        TPWM_IR_Transmitter(~gu32TransmitData);
        CLK_SysTickDelay(IR_FRAME_INTERVAL_US);
        printf("IR transmitted data 0x%x\n", ~gu32TransmitData);
        printf("CIR received data 0x%x....\n\n", gu32ReceivedData0);

        gu32TransmitData++;
    }
    while(gu32TransmitData != IR_TX_DATA_END);

    printf("CIR Sample Code Done\n\n");

    /* Stay here after the demonstration completes. */
    while(SYS->PDID);
}
