/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'CMSIS_DV_USBH_HID' 
 * Target:  'CMSIS_DV_USBH_HID' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55M1.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::USB&MDK:CORE@8.0.0 */
#define RTE_USB_Core                    /* USB Core */
/* Keil::USB&MDK:Host:HID@8.0.0 */
#define RTE_USB_Host_HID                /* USB Host HID */
/* Keil::USB&MDK:Host@8.0.0 */
#define RTE_USB_Host_0                  /* USB Host 0 */
#define RTE_USB_Host_1                  /* USB Host 1 */
#define RTE_USB_Host_2                  /* USB Host 2 */



#endif /* RTE_COMPONENTS_H */
