/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.0.0
 *
 * Project: 'CMSIS_DV_USBD_MSC'
 * Target:  'CMSIS_DV_USBD_MSC'
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File:
 */
#define CMSIS_device_header "ARMCM33.h"

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS:RTOS2:Keil RTX5&Source@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
#define RTE_CMSIS_RTOS2_RTX5_SOURCE     /* CMSIS-RTOS2 Keil RTX5 Source */
/* Keil::CMSIS-Compiler:File Interface:MDK-MW File System@1.0.1 */
#define RTE_CMSIS_Compiler_File_Interface        /* CMSIS-Compiler File Interface */
#define RTE_CMSIS_Compiler_File_Interface_MDK_MW /* CMSIS-Compiler File Interface: MDK-Middleware File System */
/* Keil::File System&MDK:CORE@8.0.2 */
#define RTE_FileSystem_Core             /* File System Core */
/* Keil::File System&MDK:Drive:RAM@8.0.2 */
#define RTE_FileSystem_Drive_RAM_0      /* File System RAM Drive 0 */

/* Keil::USB&MDK:CORE@8.0.0 */
#define RTE_USB_Core                    /* USB Core */
/* Keil::USB&MDK:Device:MSC@8.0.0 */
#define RTE_USB_Device_MSC_0            /* USB Device MSC instance 0 */

/* Keil::USB&MDK:Device@8.0.0 */
#define RTE_USB_Device_0                /* USB Device 0 */



#endif /* RTE_COMPONENTS_H */
