sbomType: Product SBOM
include:
  - path: Library/CMSIS
  - path: Library/CryptoAccelerator
  - path: Library/Device
  - path: Library/NuMaker
  - path: Library/SmartcardLib
  - path: Library/StdDriver
  - path: Library/UsbHostLib
exclude:
  - path: Document/
  - path: SampleCode/
  - path: ThirdParty/
  - path: Utilities/