name: Buildroot building

on:
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/OpenNuvoton/buildroot_2024.git'
      branches-tags:
        description: 'branches-tags'
        required: true
        default: 'master'
      board:
        description: 'board'
        required: true
        default: 'nuvoton_nuc980_ncsi'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone ${{github.event.inputs.git-address}} /opt/buildroot
        cd /opt/buildroot

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y make gcc g++ unzip git bc python3 device-tree-compiler mtd-utils

    - name: Bulid
      run: |
        mkdir /opt/firmware
        cd /opt/buildroot
        git checkout ${{github.event.inputs.branches-tags}}
        git pull origin ${{github.event.inputs.branches-tags}}

        echo '---start make---'
        make ${{github.event.inputs.board}}_defconfig
        make
        cp -r /opt/buildroot/output/images /opt/firmware

    - name : Upload buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
      uses: actions/upload-artifact@master
      with:
        name: buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
        path: /opt/firmware
