name: CppCheck

on:
  #push:
  #  branches:
  #    - '**'  # Match all branches
  #pull_request:
  #  branches:
  #    - '**'  # Match all target branches of pull requests
  workflow_dispatch:

jobs:
  build:
    name: Build project
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: cppcheck installation
        run: |
          sudo apt-get update
          sudo apt-get -qq install cppcheck

      - name: cppcheck and htmlreport
        shell: bash
        run: |
              MISSUDAD_CPPCHECK="$GITHUB_WORKSPACE/.github/CppCheck"

              cd $GITHUB_WORKSPACE

              cppcheck --version

              cppcheck --enable=all --inconclusive --std=c99 --addon="$MISSUDAD_CPPCHECK/misra.json" -j 8 --force \
                --output-file="$GITHUB_WORKSPACE/cppcheck_report.txt" --xml --xml-version=2 \
                --template="{file}:{line}:{severity}:{id}:{message}" \
                --checkers-report="$GITHUB_WORKSPACE/misra.log" \
                --suppress=staticFunction \
                --suppress=missingInclude \
                --suppress=missingIncludeSystem \
                --suppress=unusedFunction \
                --suppress=misra-c2012-2.5 \
                -I $GITHUB_WORKSPACE/Library/Device/Nuvoton/M3351/Include/ \
                -I $GITHUB_WORKSPACE/Library/StdDriver/inc/ \
                -I $GITHUB_WORKSPACE/Library/Device/Nuvoton/M3351/Include/ \
                $GITHUB_WORKSPACE/Library/StdDriver/src/canfd.c

                cppcheck-htmlreport --file="$GITHUB_WORKSPACE/cppcheck_report.txt" --report-dir=cppcheck_html --title="BSP-StdDriver MISRA Report"
                ls -al $GITHUB_WORKSPACE/cppcheck_html
