name: MDK5 building

on:
  push:
    branches-ignore:
      - main
      - master
  #pull_request:
  #  branches-ignore:
  #    - main
  #    - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: MDK5 project building
        shell: bash
        run: |
          echo "Building $GITHUB_REF_NAME"
          REPO_ROOT="$GITHUB_WORKSPACE"
          MISSUDAD_KEIL="$REPO_ROOT/.github/MissUDad/Keil"
          echo "Building $MISSUDAD_KEIL"

          set +e
          cd $MISSUDAD_KEIL
          python build.py
          retc=$?
          if [ $retc -ne 0 ]; then
            echo "❌ Build Failed:"
            cat "$MISSUDAD_KEIL/failed_logs.txt"
            cp -af "$MISSUDAD_KEIL/failed_logs.txt"
          else
            echo "🎉 All checking succeeded!" $REPO_ROOT
          fi
          set -e
          exit $retc

      - name: Prepare failed logs for email
        id: prepare_logs
        shell: bash
        if: failure() # only runs if previous step failed
        run: |
          if [[ -f failed_logs.txt ]]; then
            logs=$(cat failed_logs.txt)
            echo "logs=$logs" >> "$GITHUB_OUTPUT"

            numbered_logs=""
            IFS=',' read -ra logs <<< "$(cat failed_logs.txt)"
            i=1
            for log in "${logs[@]}"; do
              numbered_logs+="[$i] $log\n"
              ((i++))
            done
            echo -e "msglogs<<EOF\n$numbered_logs\nEOF" >> "$GITHUB_OUTPUT"
          fi

      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v5
        with:
          connection_url: ${{ secrets.MAIL_CONNECTION }}
          subject: ${{ github.repository }} [${{ github.ref_name }}] Job ${{ job.status }}
          to: wclin@nuvoton.com
          #to: ${{ secrets.MAIL_TO }}
          #cc: ${{ secrets.MAIL_CC }}
          from: Github Action Workflow <wosayttn@gmail.com>
          attachments: ${{ steps.prepare_logs.outputs.logs }}
          body: |
            Hello,

            The build has completed. Please find the attached log file for details.

            Failure:
            ${{ steps.prepare_logs.outputs.msglogs }}

            Best regards,
            NuMicro Actions

      - name: Collect artifacts with directory structure
        shell: bash
        run: |
          mkdir -p artifacts
          find SampleCode -type f -name "*.bin" -exec cp --parents {} artifacts/ \;

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-artifacts
          path: artifacts/
